version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: gym_postgres
    environment:
      POSTGRES_DB: gym_management
      POSTGRES_USER: gym_admin
      POSTGRES_PASSWORD: gym_secure_2024
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  # Backend API
  backend:
    build: ./backend
    container_name: gym_backend
    environment:
      DATABASE_URL: postgresql://gym_admin:gym_secure_2024@postgres:5432/gym_management
      JWT_SECRET: your_jwt_secret_key_here
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped

  # Frontend
  frontend:
    build: .
    container_name: gym_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: gym_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

volumes:
  postgres_data: